### ISSUE TITLE
Death Knight T12 Tank Set 2p Bonus not working

### ISSUE THREAD

**Issue by darkmaster2133** [wowsims/cata#1029]
**Describe the bug**
Death Knight T12 Tank Set 2p Bonus not working.
It is supposed to make attacks behave as if the target has two diseases active, but it does not.

**To Reproduce**
1. Apply Tank 2p on Frost DPS
2. Remove Plague Strike from rotation
3. Sim
4. Compare Obliterate damage to if you were casting Plague Strike

**Expected behavior**
Obliterate damage should not change

**Comment by 1337LutZ** [comment]
@darkmaster2133 it's currently adding on top of diseases. Until we find proof that it adds on top as instead of a default 2 baseline it should probably stay as is.

I couldn't find any proof that it will add on top of other diseases as in; 2 + 2 (from 2P), since that would make it incredibly strong for Frost (~800DPS) and Unholy (~1500DPS).

**Comment by 1337LutZ** [comment]
Closing it for now until we can determine the actual behavior from PTR.
