### ISSUE TITLE
[Hunter] dwarf and gun racial

### ISSUE THREAD

**Issue by Namooro** [wowsims/cata#493]
**Describe the bug**
Sim doesnt count1% crit racial increase for Dwarf hunter wearing gun
**To Reproduce**
1) Sim pre-bis equip for worgen hunter in Survival spec: https://wowsims.github.io/cata/hunter/survival/#eJzlUk1oE1EQ3pnZJruvlb4GhdcguFkRSqFls7lED+6mpx48BPFQPRlotYKHUDxUTxFFYkAQBU2CCkZBKSp6azyVgv/K7qn+gYgS0kPBFgt6kr7Na8FrDp78eMybmfd9M8Pw2B4DOPgwDUUoA1QB7gMsAHwAWAYoIZQRHiOMmQaMK0pCSzZ76hTLnyycnpoxejkmnwFL8IWQxJplm3M1fSmk9yExk/+pkk3r14n18+/zJFasTjRUARbnaz9IvDFYH19vkrggXxpVYoz/kulGygaNbeOXnpO4NmjrUqNJ4ucm2THpq4KLsuAty45JWaTs40/aJC6qDrL1l63WOq+3I/t6PrJlaeO8/ojEuRSLirYDEoFS2f0GOjvyOIFHe2bhMsDwQ2S/QftPkXC6VezTxrAIFXDYKNvNdyW3G8ghSz6M0zTNqv+FKcVd9RwYePc2wor3FHc6mRE347gjTsZ15K2Om3bTmXR6EYVxp4X8bgvFlQCtaoBD91roXA3wJeohxj+h9g2ZADuW0BkybRmPnCXVJ+vf3vQO+xXS7Baanehr0R9Q+f3+YL0W4ZW3V2VCL3WsgyUvtzWi+wCLcz/hTO/BwolJ61Bh5vjUKWtCxIf/8QfJn/e7oZcmX3TDP5C9eSPX1Tx/obOtUsPM1UAt8KO3WUv3NwDI4pwv
2) Switch race for dwarf and sim it again.

**Expected behavior**
Sims should be close to equal since the sim include gun as the main weapon, since worgen racial (1% crit) is the same as the dwarf racial (1% crit with guns).

**Actual behavior**
Sim shows the quite drastic difference in dps (about 100 dps)

**Comment by rosenrusinov** [comment]
Dwarf racial and Worgen racial are not the same which is why you see this dps difference. The Dwarf gun racial works in the sim and properly adds 1% crit to all ranged attacks done by the hunter. The worgen racial on the other hand gives general crit which also is scaled on the pet. You can confirm the racial works by checking the reported crit value in the UI increasing when you equip a gun vs a bow with dwarf selected (easiest to check is with the pvp weapons as they have the same stats but only different type)
