### ISSUE TITLE
Add the possiblity to choose presence as a DK

### ISSUE THREAD

**Issue by jacksun78** [wowsims/cata#761]
Hello,

I would need to be able to change rpensece between frost and unholy as a DK dps.
This in order to sim several setups.

For example, it's said everywhere that all Frost K should play full mastery and unholy presence but I get better results ingame with full haste and frost presence. I would like to be able to see if it's totally stuff related and will no longer be viable later or if it's something the community missed.

Anyway being able to switch presence in the buffs instead of having it fixed in the Rotation would be a plus

Thanks

**Comment by rosenrusinov** [comment]
The presence can already be changed in the Rotation and it is not an external buff which is why its not present in the buff options. In the Saved Rotation options you can select from the default APL and then change your desired presence in the pre pull action.

![image](https://github.com/wowsims/cata/assets/5707996/0cefae0f-05c5-4816-b4e4-b96c4417af22)
